const KEY="rewear_data_v1";
const seed={
  user:{name:"Sanket Yede",email:"sanket@example.com",location:"Pune, Maharashtra"},
  listings:[
    {id:1,name:"Classic Denim Jacket",category:"Jacket",brand:"Levi's",size:"M",condition:"Excellent",value:1800,location:"Pune, Maharashtra",owner:"Aarav",emoji:"🧥",color:"blue"},
    {id:2,name:"Oversized Linen Shirt",category:"Shirt",brand:"Zara",size:"L",condition:"Like New",value:1200,location:"Mumbai, Maharashtra",owner:"Meera",emoji:"👔",color:"cream"},
    {id:3,name:"Straight Fit Jeans",category:"Jeans",brand:"Uniqlo",size:"M",condition:"Good",value:900,location:"Pune, Maharashtra",owner:"Rohan",emoji:"👖",color:"indigo"},
    {id:4,name:"Floral Midi Dress",category:"Dress",brand:"H&M",size:"S",condition:"Like New",value:1400,location:"Nashik, Maharashtra",owner:"Isha",emoji:"👗",color:"pink"},
    {id:5,name:"Everyday Sneakers",category:"Sneakers",brand:"Adidas",size:"9",condition:"Excellent",value:1600,location:"Pune, Maharashtra",owner:"Kabir",emoji:"👟",color:"white"},
    {id:6,name:"Essential Hoodie",category:"Hoodie",brand:"Nike",size:"L",condition:"Excellent",value:1700,location:"Aurangabad, Maharashtra",owner:"Neha",emoji:"🧥",color:"green"},
    {id:7,name:"Cotton Casual Shirt",category:"Shirt",brand:"Uniqlo",size:"M",condition:"Good",value:700,location:"Pune, Maharashtra",owner:"Vikram",emoji:"👕",color:"white"},
    {id:8,name:"Minimal Black Dress",category:"Dress",brand:"H&M",size:"S",condition:"Excellent",value:1100,location:"Mumbai, Maharashtra",owner:"Ananya",emoji:"👗",color:"black"}
  ],
  requests:[
    {id:101,itemId:1,from:"Sanket",offered:"Straight Fit Jeans",status:"Pending",date:"24 Aug 2026"},
    {id:102,itemId:4,from:"Isha",offered:"Cotton Casual Shirt",status:"Accepted",date:"22 Aug 2026"}
  ],
  messages:[
    {id:1,person:"Aarav",item:"Classic Denim Jacket",text:"Hey! Would you be interested in swapping for your jeans?",me:false},
    {id:2,person:"Aarav",item:"Classic Denim Jacket",text:"Absolutely. The condition is excellent and I can meet near Pune.",me:true},
    {id:3,person:"Aarav",item:"Classic Denim Jacket",text:"Sounds good. How about Saturday afternoon?",me:false}
  ],
  swaps:12
};
function getData(){let d=localStorage.getItem(KEY);if(!d){localStorage.setItem(KEY,JSON.stringify(seed));return structuredClone(seed)}return JSON.parse(d)}
function saveData(d){localStorage.setItem(KEY,JSON.stringify(d))}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function qs(k){return new URLSearchParams(location.search).get(k)}
function updateNav(){const d=getData();const u=document.getElementById("navUser");if(u)u.textContent=d.user.name;const b=document.getElementById("loginBtn");if(b&&d.user.email)b.textContent="Logout",b.href="#",b.onclick=()=>{localStorage.removeItem("rewear_auth");location.reload()}}
document.addEventListener("DOMContentLoaded",updateNav);
function card(x){return `<article class="product"><a href="item.html?id=${x.id}"><div class="product-img">${x.image?`<img src="${esc(x.image)}" alt="${esc(x.name)}">`:`<span>${x.emoji||"👕"}</span>`}</div></a><div class="product-body"><span class="pill">${esc(x.category)}</span><h3>${esc(x.name)}</h3><div class="meta">${esc(x.brand)} • Size ${esc(x.size)} • ${esc(x.condition)}</div><div class="meta">📍 ${esc(x.location)}</div><div class="value">Estimated swap value ₹${Number(x.value).toLocaleString("en-IN")}</div></div></article>`}
function renderFeatured(){const d=getData(),el=document.getElementById("featuredGrid");if(el)el.innerHTML=d.listings.slice(0,4).map(card).join("")}
function updateHomeStats(){const d=getData();document.getElementById("statListings")?.replaceChildren(document.createTextNode(d.listings.length));document.getElementById("statSwaps")?.replaceChildren(document.createTextNode(d.swaps))}
function renderListings(){const d=getData(),grid=document.getElementById("listingGrid");if(!grid)return;const q=(document.getElementById("search")?.value||"").toLowerCase(),c=document.getElementById("category")?.value,s=document.getElementById("size")?.value,co=document.getElementById("condition")?.value;let arr=d.listings.filter(x=>(!q||`${x.name} ${x.brand} ${x.location}`.toLowerCase().includes(q))&&(!c||x.category===c)&&(!s||x.size===s)&&(!co||x.condition===co));grid.innerHTML=arr.length?arr.map(card).join(""):`<div class="empty" style="grid-column:1/-1">No clothing matches your filters. Try a broader search.</div>`}
function renderItem(){const d=getData(),x=d.listings.find(a=>a.id==qs("id")),el=document.getElementById("itemDetail");if(!el)return;if(!x){el.innerHTML='<div class="empty">Item not found.</div>';return}el.innerHTML=`<div class="detail"><div class="detail-image">${x.image?`<img src="${esc(x.image)}" alt="${esc(x.name)}">`:x.emoji||"👕"}</div><div><span class="eyebrow">${esc(x.category)}</span><h1>${esc(x.name)}</h1><p class="hero p">Listed by <b>${esc(x.owner)}</b> • ${esc(x.location)}</p><div class="detail-info"><div class="info-box"><small>BRAND</small><b>${esc(x.brand)}</b></div><div class="info-box"><small>SIZE</small><b>${esc(x.size)}</b></div><div class="info-box"><small>CONDITION</small><b>${esc(x.condition)}</b></div><div class="info-box"><small>SWAP VALUE</small><b>₹${Number(x.value).toLocaleString("en-IN")}</b></div></div><div class="notice">Fair swap tip: choose an item with a similar estimated value, then use chat to negotiate if values differ.</div><a class="btn btn-primary" href="swap.html?id=${x.id}">Request a swap</a> <a class="btn btn-outline" href="chat.html?person=${encodeURIComponent(x.owner)}">Message owner</a></div></div>`}
function renderSwap(){const d=getData(),x=d.listings.find(a=>a.id==qs("id")),el=document.getElementById("swapPage");if(!el)return;if(!x){el.innerHTML='<div class="empty">Select a clothing item from the marketplace first.</div>';return}const options=d.listings.filter(a=>a.owner!==d.user.name&&a.id!==x.id);el.innerHTML=`<span class="eyebrow">SWAP REQUEST</span><h1>Offer an item for exchange</h1><p>Requesting <b>${esc(x.name)}</b> from ${esc(x.owner)}. Choose one of your available offers.</p><div class="panel"><h2>Target item</h2>${card(x)}</div><form id="swapForm" class="panel"><label>Your offered item<select id="offer">${options.map(a=>`<option value="${a.id}">${esc(a.name)} — ₹${a.value}</option>`).join("")}</select></label><label>Message<textarea id="swapMessage" rows="4" style="width:100%;border:1px solid var(--line);border-radius:9px;padding:12px;font:inherit" placeholder="Explain why this is a fair swap…"></textarea></label><button class="btn btn-primary">Send swap request</button></form>`;document.getElementById("swapForm").onsubmit=e=>{e.preventDefault();const offer=d.listings.find(a=>a.id==document.getElementById("offer").value);d.requests.unshift({id:Date.now(),itemId:x.id,from:d.user.name,offered:offer.name,status:"Pending",date:new Date().toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"})});saveData(d);alert("Swap request sent successfully!");location.href="dashboard.html"}}
function initLogin(){const f=document.getElementById("loginForm");if(!f)return;f.onsubmit=e=>{e.preventDefault();const email=document.getElementById("email").value.trim(),pass=document.getElementById("password").value;if(!email||pass.length<4)return;localStorage.setItem("rewear_auth","1");const d=getData();d.user.email=email;d.user.name=email.split("@")[0].replace(/[._-]/g," ").replace(/\b\w/g,c=>c.toUpperCase());saveData(d);location.href="dashboard.html"}}
function demoRegister(){localStorage.setItem("rewear_auth","1");location.href="dashboard.html"}
function renderDashboard(){const d=getData();const ml=document.getElementById("myListings"),req=document.getElementById("requests");if(ml)ml.innerHTML=d.listings.slice(0,3).map(x=>`<div class="mini-item"><div><b>${esc(x.name)}</b><div class="meta">${esc(x.category)} • ${esc(x.condition)}</div></div><b>₹${x.value}</b></div>`).join("");if(req)req.innerHTML=d.requests.map(r=>`<div class="request"><div><b>${esc(r.from)}</b> offered <b>${esc(r.offered)}</b><div class="meta">${esc(r.date)}</div></div><span class="pill ${r.status==="Accepted"?"success":""}">${esc(r.status)}</span></div>`).join("")||'<div class="empty">No swap requests yet.</div>'}
function openListingForm(){document.getElementById("listingForm")?.classList.remove("hidden")}function closeListingForm(){document.getElementById("listingForm")?.classList.add("hidden")}
function addListing(e){e.preventDefault();const d=getData();d.listings.unshift({id:Date.now(),name:document.getElementById("newName").value,category:document.getElementById("newCategory").value,brand:document.getElementById("newBrand").value,size:document.getElementById("newSize").value,condition:document.getElementById("newCondition").value,location:document.getElementById("newLocation").value,value:Number(document.getElementById("newValue").value),owner:d.user.name,emoji:"👕",image:document.getElementById("newImage").value});saveData(d);closeListingForm();renderDashboard();alert("Listing published successfully!")}
function calculateValue(){const c=document.getElementById("calcCategory").value,b=document.getElementById("calcBrand").value,co=document.getElementById("calcCondition").value;base={Shirt:650,Jacket:1300,Jeans:900,Dress:1000,Sneakers:1300,Hoodie:1100}[c];brandMul={"H&M":1,"Zara":1.25,"Levi's":1.3,"Nike":1.35,"Adidas":1.25,"Uniqlo":1.15}[b];condMul={"Like New":1.2,"Excellent":1,"Good":.72}[co];const v=Math.round(base*brandMul*condMul/50)*50;document.getElementById("calcResult").textContent="₹ "+v.toLocaleString("en-IN")}
let activePerson="Aarav";function initChat(){renderChatList();loadChat(activePerson);document.getElementById("chatForm").onsubmit=e=>{e.preventDefault();const inp=document.getElementById("chatInput"),txt=inp.value.trim();if(!txt)return;const d=getData();d.messages.push({id:Date.now(),person:activePerson,item:"Classic Denim Jacket",text:txt,me:true});saveData(d);inp.value="";loadChat(activePerson)}}
function renderChatList(){const d=getData(),people=[...new Set(d.messages.map(m=>m.person))];document.getElementById("chatList").innerHTML=people.map(p=>`<div class="chat-person ${p===activePerson?"active":""}" onclick="activePerson='${esc(p)}';renderChatList();loadChat(activePerson)"><b>${esc(p)}</b><br><small>${esc(d.messages.find(m=>m.person===p)?.item||"Swap conversation")}</small></div>`).join("")}
function loadChat(p){const d=getData(),msgs=d.messages.filter(m=>m.person===p),el=document.getElementById("messages");document.getElementById("chatTitle").textContent=p+" • "+(msgs[0]?.item||"Swap");el.innerHTML=msgs.map(m=>`<div class="bubble ${m.me?"me":""}">${esc(m.text)}</div>`).join("");el.scrollTop=el.scrollHeight}
function renderAdmin(){const d=getData(),stats=document.getElementById("adminStats");stats.innerHTML=[["Listings",d.listings.length],["Successful swaps",d.swaps],["Swap requests",d.requests.length],["Active users",Math.max(8,d.listings.length+4)]].map(a=>`<div class="admin-stat"><span>${a[0]}</span><b>${a[1]}</b></div>`).join("");document.getElementById("adminTable").innerHTML=d.listings.slice(0,8).map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${esc(x.owner)}</td><td>${esc(x.category)}</td><td>₹${x.value}</td><td><span class="pill success">Active</span></td><td><button class="btn btn-outline" onclick="removeListing(${x.id})">Remove</button></td></tr>`).join("")}
function removeListing(id){const d=getData();d.listings=d.listings.filter(x=>x.id!==id);saveData(d);renderAdmin();renderFeatured?.();alert("Listing removed by admin.")}
function resetDemo(){localStorage.removeItem(KEY);location.reload()}
